export const MARCAS_DISPONIBLES = [
  { id: 'iphone', nombre: 'iPhone' },
  { id: 'samsung', nombre: 'Samsung' },
  { id: 'otras', nombre: 'Otras marcas' },
];

// Listas de modelos "canónicos" (nombre y formato consistente) que se
// cargan como carpetas de Stock apenas el negocio elige trabajar con
// esa marca. La idea es que la gente elija de un desplegable en vez de
// escribir el modelo a mano y terminar con carpetas duplicadas por una
// mayúscula o un espacio de más (ej. "iPhone 13 Pro" vs "iphone 13 pro").
// "Otras marcas" no tiene catálogo: esas carpetas se siguen cargando a mano.
export const CATALOGO_MODELOS: Record<string, string[]> = {
  iphone: [
    'iPhone 7',
    'iPhone 7 Plus',
    'iPhone 8',
    'iPhone 8 Plus',
    'iPhone X',
    'iPhone XR',
    'iPhone XS',
    'iPhone XS Max',
    'iPhone 11',
    'iPhone 11 Pro',
    'iPhone 11 Pro Max',
    'iPhone SE (2020)',
    'iPhone 12',
    'iPhone 12 mini',
    'iPhone 12 Pro',
    'iPhone 12 Pro Max',
    'iPhone 13',
    'iPhone 13 mini',
    'iPhone 13 Pro',
    'iPhone 13 Pro Max',
    'iPhone SE (2022)',
    'iPhone 14',
    'iPhone 14 Plus',
    'iPhone 14 Pro',
    'iPhone 14 Pro Max',
    'iPhone 15',
    'iPhone 15 Plus',
    'iPhone 15 Pro',
    'iPhone 15 Pro Max',
    'iPhone 16',
    'iPhone 16 Plus',
    'iPhone 16 Pro',
    'iPhone 16 Pro Max',
    'iPhone 16e',
    'iPhone 17',
    'iPhone 17 Pro',
    'iPhone 17 Pro Max',
    'iPhone 17e',
    'iPhone Air',
  ],
  samsung: [
    'Galaxy S8',
    'Galaxy S8+',
    'Galaxy S9',
    'Galaxy S9+',
    'Galaxy Note 9',
    'Galaxy S10',
    'Galaxy S10+',
    'Galaxy S10e',
    'Galaxy Note 10',
    'Galaxy Note 10+',
    'Galaxy S20',
    'Galaxy S20+',
    'Galaxy S20 Ultra',
    'Galaxy Note 20',
    'Galaxy Note 20 Ultra',
    'Galaxy Z Flip',
    'Galaxy Z Fold 2',
    'Galaxy S21',
    'Galaxy S21+',
    'Galaxy S21 Ultra',
    'Galaxy S21 FE',
    'Galaxy Z Flip 3',
    'Galaxy Z Fold 3',
    'Galaxy A32',
    'Galaxy A52',
    'Galaxy A72',
    'Galaxy S22',
    'Galaxy S22+',
    'Galaxy S22 Ultra',
    'Galaxy Z Flip 4',
    'Galaxy Z Fold 4',
    'Galaxy A33',
    'Galaxy A53',
    'Galaxy A73',
    'Galaxy S23',
    'Galaxy S23+',
    'Galaxy S23 Ultra',
    'Galaxy S23 FE',
    'Galaxy Z Flip 5',
    'Galaxy Z Fold 5',
    'Galaxy A34',
    'Galaxy A54',
    'Galaxy S24',
    'Galaxy S24+',
    'Galaxy S24 Ultra',
    'Galaxy S24 FE',
    'Galaxy Z Flip 6',
    'Galaxy Z Fold 6',
    'Galaxy A35',
    'Galaxy A55',
    'Galaxy S25',
    'Galaxy S25+',
    'Galaxy S25 Ultra',
    'Galaxy S25 Edge',
    'Galaxy Z Flip 7',
    'Galaxy Z Fold 7',
    'Galaxy A36',
    'Galaxy A56',
  ],
};

export function normalizarNombreModelo(nombre: string) {
  return nombre.trim().toLowerCase().replace(/\s+/g, ' ');
}
